spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/store
    driver-class-name: org.mariadb.jdbc.Driver
    username: store
    password: 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate.hbm2ddl.auto: update
    # hibernate:
    #  format_sql: true
    #  ddl-auto: update

  jwt:
    secret: test # 암호화 (터미널에서 echo '~~~' | base64)
